name: Weekly Blog
on:
  schedule:
    - cron: "0 9 * * 1"   # her pazartesi sabah 9'da
  workflow_dispatch:      # manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install feedparser
    - run: python agent.py
    - name: Commit blog post
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add weekly_blog.md
        git commit -m "Add weekly blog"
        git push
