name: Daily AI Blog

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install feedparser openai

    - name: Run script
      run: python agent.py --category=ai
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Commit blog post
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add daily_ai.md
        git commit -m "Add daily AI blog" || echo "No changes"
        git push
